package com.developercfk.main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.developercfk.dao.AdministratorDao;
import com.developercfk.pojo.Administrador;
import com.developercfk.pojo.Empleado;
import com.developercfk.utilidades.GestionUtil;
import com.developercfk.utilidades.HibernateUtil;
import com.developercfk.view.CreateAdministrator;
import com.developercfk.view.SessionUser;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author CFK Local
 */
public class Login extends javax.swing.JFrame {

    private final Session session;
    private Empleado empleado;
    private final AdministratorDao administratorDao;
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        session = HibernateUtil.getSessionFactory().openSession();
        administratorDao = new AdministratorDao(session);
        initComponents();
        this.setLocationRelativeTo(null);
        showAndHideButtonCreateAdmintrator();
        
        
        
    }
    
   
    private void openCreateAdministratorPanel(){
        
        CreateAdministrator createAdminPanel = new CreateAdministrator();
        createAdminPanel.setSession(session);
        createAdminPanel.setFrame(this);
        createAdminPanel.setPanel(jPanelLogin);
        GestionUtil.intercambiarJPanel(this, jPanelLogin, createAdminPanel);
    }
    
    private void openSessionUserPanel(){
        
        if(verificateUserAndPassword(jTextFieldUsername.getText(), jPasswordField.getText())){
            
            SessionUser sessionUserPanel = new SessionUser(this.session, empleado);
            GestionUtil.intercambiarJPanel(this, jPanelLogin, sessionUserPanel);
        }else{
            
            JOptionPane.showMessageDialog(null, "Incorrect username or password", "Connexion error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private boolean tableAdministratorIsEmpty(){
       
        boolean b;
       
        
        b = administratorDao.ListAdministrator().isEmpty();
        
        return b;
    }
    
    private void showAndHideButtonCreateAdmintrator(){
        
        
        if(tableAdministratorIsEmpty()){
           
            jButtonNewAdministrator.setVisible(true);
            jButtonLogin.setVisible(false);
        }else{
            jButtonNewAdministrator.setVisible(false);
            jButtonLogin.setVisible(true);
        }  
    }
    
    private boolean verificateUserAndPassword(String userName, String password){
        
        boolean adminEncontrado = false;
       
        List<Administrador> listAdmin = administratorDao.ListAdministrator();
        
        for (int i = 0; i < listAdmin.size(); i++) {
            
            Empleado e = listAdmin.get(i).getEmpleado();
            
            if( e.getNombreUsuario().equals(userName) && e.getContrasenaUsuario().equals(password) ){
                
                empleado = e;
                adminEncontrado = true;
                return adminEncontrado;
            }
        }
        
        return adminEncontrado;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonNewAdministrator = new javax.swing.JButton();
        jTextFieldUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelLogin.setBackground(new java.awt.Color(204, 204, 255));
        jPanelLogin.setMaximumSize(new java.awt.Dimension(692, 529));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(692, 529));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(700, 550));
        jPanelLogin.setRequestFocusEnabled(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/store .png"))); // NOI18N
        jLabelLogo.setText("Gestion");

        jLabelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/usuario .png"))); // NOI18N
        jLabelUsername.setText("Username :");

        jLabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/desbloqueado .png"))); // NOI18N
        jLabelPassword.setText("Password :");

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/entrar .png"))); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/cerrar-sesion .png"))); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonNewAdministrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/developercfk/img/adduser_1103 .png"))); // NOI18N
        jButtonNewAdministrator.setText("New Administrator");
        jButtonNewAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewAdministratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNewAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelLogin.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonNewAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewAdministratorActionPerformed
      
        openCreateAdministratorPanel();
    }//GEN-LAST:event_jButtonNewAdministratorActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
      
       
    int resp = JOptionPane.showConfirmDialog(null , "You are about to close the application. Are you sure?","Alert!", JOptionPane.YES_NO_OPTION );
            if(resp == 0){
                session.clear();
                session.close();
                this.dispose();
            }

    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
       
        openSessionUserPanel();

    }//GEN-LAST:event_jButtonLoginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonNewAdministrator;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    public Session getSession() {
        return session;
    }
}
